### PR TITLE
Fixing healtcheck by sending appropriate key/value schemas

### LINKED ISSUE #94: HealthCheck is failing
# Expected Behavior

A new Stream named "StreamRegistryHealthCheck" should be inserted successfully as part of HealthCheck

# Actual Behavior

The HealthCheck fails with the error "Schema Parse Exception". 

# Steps to Reproduce

Please include a numbered list of steps that other people can 
use to recreate the "Actual Behavior."

1. Start the Application
2. hit the healthcheck endpoint http://localhost:8081/private/healthcheck

# Additional Information

Root cause of the bug: We recently introduced validation of inputs schemas against confluent schema registry

### PR DESCRIPTION
**Pull request by prabhakar1983**
# stream-registry PR

- Fixed the HealthCheck
- Fixes #94 

### Changed
* Passed an appropriate schema while inserting a Stream during HealthCheck

# PR Checklist Forms

- [x] CHANGELOG.md updated
- [x] Reviewer assigned
- [x] PR assigned (presumably to submitter)
- [x] Labels added (enhancement, bug, documentation)

### CODE REVIEW

File: core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java [hunk 1]
```diff
@@ -178,10 +179,16 @@ private Stream createCanaryStream() {
     }
 
     private Schema createSampleSchema() {
+        org.apache.avro.Schema sampleSchema = SchemaBuilder.builder("com.streamplatform.healthcheck")
```
Comment (prabhakar1983) [inline core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java]: We recently added Schema Validation. So, a valid schema is now necessary for inserting a Stream

File: core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+
+import org.junit.Assert;
+import org.junit.Test;
+
+import com.homeaway.streamplatform.streamregistry.resource.BaseResourceIT;
+
+public class StreamRegistryHealthCheckIT extends BaseResourceIT {
+
+    @Test
+    public void testHealthCheck() {
```
Comment (prabhakar1983) [inline core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java]: @arunvasudevan 
`mvn clean verify` runs this test successfully.'

Also, verified that the bad schema throws an exception

File: core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+package com.homeaway.streamplatform.streamregistry.health;
+
+import com.codahale.metrics.health.HealthCheck;
+
+import org.junit.Assert;
+import org.junit.Before;
+import org.junit.Test;
+
+import com.homeaway.streamplatform.streamregistry.resource.BaseResourceIT;
+
```
Comment (arunvasudevan) [inline core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java]: Add javadocs for the class

Comment (prabhakar1983) [reply core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java]: @arunvasudevan add JavaDoc for the Test Class.

File: core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java [hunk 4]
```diff
@@ -136,10 +138,10 @@ private synchronized void setConsumerRegistrationHealthy(boolean value) {
     protected synchronized Result check() {
         try {
             validateCreateStream();
-            validateStateStore();
             validateKStreamState();
             validateProducerRegistration();
             validateConsumerRegistration();
+            validateStateStore();
```
Comment (prabhakar1983) [inline core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java]: @neoword 
moved the StreamLookupValidation to the end so that GlobalKTable has enough time to pick the newly inserted stream. (avoided having any sleep statments)

File: core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java [hunk 5]
```diff
@@ -67,16 +68,25 @@
...
+    private String region;
+    private int healthcheckStreamReplicationFactor;
 
-    public StreamRegistryHealthCheck(ManagedKStreams managedKStreams, StreamResource streamResource, MetricRegistry metricRegistry) {
+    /**
+     * Constructor called from BaseResourceIT.java for overriding the
+     *      replication-factor to 1 - there is only one broker in IntegrationTest cluster
+     *      region - Build environment does not have MPAAS_REGION env variables.
+     */
+    public StreamRegistryHealthCheck(ManagedKStreams managedKStreams, StreamResource streamResource, MetricRegistry metricRegistry,
```
Comment (neoword) [inline core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java]: make this constructor package scope?
